# Generated by Django 6.0.5 on 2026-05-27 20:15

from django.db import migrations, models

def fill_is_member(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')
    for user in CustomUser.objects.all():
        user.is_member = True
        user.save()

def reverse(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(fill_is_member, reverse),
    ]
