# Generated by Django 6.0.5 on 2026-05-27 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_is_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_member',
        ),
    ]
