# Generated by Django 6.0.5 on 2026-05-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_is_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('M', 'Manager'), ('A', 'Admin'), ('S', 'Staff'), ('R', 'Regular'), ('V', 'Visitor')], default='V', max_length=1),
        ),
    ]
