# Generated by Django 6.0.5 on 2026-06-12 08:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('E', 'Eur'), ('U', 'Usr'), ('C', 'Cny')], default='E', max_length=1)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('code', models.CharField(max_length=5)),
                ('branch_code', models.CharField(max_length=5)),
                ('rib_key', models.CharField(max_length=2)),
                ('swift', models.CharField(max_length=12, verbose_name='SWIFT')),
                ('holder_name', models.CharField(max_length=80)),
                ('adresse', models.CharField(blank=True, max_length=80, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=5, null=True)),
                ('country_key', models.CharField(max_length=4)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankStatementFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.FileField(upload_to='bank_statements/')),
                ('archived', models.BooleanField(default=False)),
                ('date_imported', models.DateField(auto_now_add=True)),
                ('checked', models.BooleanField(default=False)),
                ('date_generated', models.DateField(blank=True, null=True)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('company_code', models.CharField(max_length=100)),
                ('company_address', models.CharField(max_length=100)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_phone', models.CharField(max_length=100)),
                ('company_website', models.CharField(blank=True, max_length=100, null=True)),
                ('company_logo', models.ImageField(upload_to='company_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyBank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('swift', models.CharField(max_length=12, verbose_name='SWIFT')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('record_code', models.CharField(max_length=3)),
                ('bank_code', models.CharField(max_length=7)),
                ('date', models.DateField()),
                ('label', models.CharField(blank=True, max_length=45, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('credit_or_debit', models.CharField(choices=[('C', 'Credit'), ('D', 'Debit'), ('N', 'Label')], max_length=1)),
                ('pointed', models.BooleanField(default=False)),
                ('date_pointed', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
