# Generated by Django 3.2 on 2022-11-06 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bank', models.CharField(max_length=60)),
                ('bank_code', models.CharField(max_length=20)),
                ('branch_code', models.CharField(max_length=8)),
                ('bic', models.CharField(max_length=12)),
                ('bank_adresse', models.CharField(blank=True, max_length=80)),
                ('country_bank_code', models.CharField(max_length=5)),
                ('country_key', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='AccountNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=15)),
                ('rib_key', models.CharField(max_length=10)),
                ('iban', models.CharField(max_length=20)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.bank')),
            ],
        ),
    ]
