# Generated by Django 6.0.5 on 2026-05-12 14:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=15)),
                ('rib_key', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_bank', models.CharField(max_length=60)),
                ('bank_code', models.CharField(max_length=20)),
                ('branch_code', models.CharField(max_length=8)),
                ('bic', models.CharField(max_length=12)),
                ('bank_adresse', models.CharField(blank=True, max_length=80)),
                ('country_bank_code', models.CharField(max_length=5)),
                ('country_key', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='BankStatementFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('date_imported', models.DateField(auto_now_add=True)),
                ('date_generated', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('company_code', models.CharField(max_length=100)),
                ('company_address', models.CharField(max_length=100)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_phone', models.CharField(max_length=100)),
                ('company_website', models.CharField(max_length=100)),
                ('company_logo', models.ImageField(upload_to='company_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='NewBalanceAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrolling_nb', models.CharField(max_length=3)),
                ('bank_code', models.CharField(max_length=7)),
                ('account_number', models.CharField(max_length=15)),
                ('new_balance_date', models.DateTimeField()),
                ('amount_credit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_debit', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrolling_nb', models.CharField(max_length=3)),
                ('bank_code', models.CharField(max_length=7)),
                ('account_number', models.CharField(max_length=15)),
                ('operation_date', models.DateField()),
                ('operation_name', models.CharField(max_length=10)),
                ('amount_credit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_debit', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
