# Generated by Django 3.2 on 2022-11-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_remove_accountnumber_iban'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_selected', models.CharField(max_length=15)),
                ('date_imported', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SelectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_document', models.CharField(max_length=15)),
                ('date_selected', models.DateField(max_length=10)),
            ],
        ),
    ]
