# Generated by Django 6.0.5 on 2026-06-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(choices=[('Indian/Reunion', 'Indian/Reunion'), ('Europe/Paris', 'Europe/Paris')], default='Indian/Reunion', max_length=50)),
                ('react_bundle_name', models.CharField(default='index', max_length=100)),
                ('stripe_api_key', models.CharField(blank=True, max_length=110, null=True)),
                ('stripe_test_api_key', models.CharField(blank=True, max_length=110, null=True)),
                ('stripe_mode_test', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
