# Generated by Django 6.0.5 on 2026-05-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementfile',
            name='state_file',
            field=models.CharField(choices=[('S', 'Selected'), ('P', 'Prechared'), ('C', 'Charged')], default='S', max_length=1),
        ),
    ]
