# Generated by Django 6.0.5 on 2026-06-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_appconfig'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companybank',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='companybank',
            constraint=models.UniqueConstraint(fields=('company', 'swift'), name='unique_company_swift'),
        ),
    ]
