# Generated by Django 3.2 on 2022-11-10 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_importingdocument_selectdocument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importingdocument',
            old_name='name_selected',
            new_name='name_document',
        ),
        migrations.RenameField(
            model_name='selectdocument',
            old_name='name_document',
            new_name='selected_document',
        ),
    ]
