# Generated by Django 6.0.5 on 2026-05-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_bankstatementfile_state_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatementfile',
            name='name',
            field=models.FileField(upload_to='bank_statements/'),
        ),
    ]
