# Generated by Django 6.0.5 on 2026-05-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_alter_bankstatementfile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementfile',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
