# Generated by Django 6.0.5 on 2026-05-15 12:27

from django.db import migrations, models


def populate_archived(apps, schema_editor):
    BankStatementFile = apps.get_model('bank', 'BankStatementFile')
    for obj in BankStatementFile.objects.all():
        if obj.state_file == "C":
            obj.archived = True
        else:
            obj.archived = False
        obj.save()


def reverse(apps, schema_editor):
    BankStatementFile = apps.get_model('bank', 'BankStatementFile')
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_bankstatementfile_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementfile',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(populate_archived, reverse)
    ]
