# Generated by Django 6.0.5 on 2026-05-15 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_bankstatementfile_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankstatementfile',
            name='state_file',
        ),
    ]
