# Generated by Django 3.2 on 2022-11-12 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_fileupload_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='date',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='created_at',
            field=models.DateField(),
        ),
    ]
