# Generated by Django 6.0.5 on 2026-05-15 18:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_remove_bankstatementfile_state_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='bank_adresse',
            new_name='adresse',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='bank_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='name_bank',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='country_bank_code',
            new_name='zip_code',
        ),
        migrations.AddField(
            model_name='bank',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='holder_name',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='rib_key',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
