# Generated by Django 3.2 on 2022-11-12 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_auto_20221112_0815'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
