# Generated by Django 6.0.5 on 2026-05-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_rename_bank_adresse_bank_adresse_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='amount_credit',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='operation',
            old_name='operation_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='operation',
            old_name='operation_name',
            new_name='operation_label',
        ),
        migrations.RenameField(
            model_name='operation',
            old_name='enrolling_nb',
            new_name='record_code',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='amount_debit',
        ),
        migrations.AddField(
            model_name='operation',
            name='credit_or_debit',
            field=models.CharField(choices=[('C', 'Credit'), ('D', 'Debit')], default=0.0, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operation',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
