# Generated by Django 6.0.5 on 2026-05-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_rename_amount_credit_operation_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='branch_code',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='bank',
            name='code',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='bank',
            name='rib_key',
            field=models.CharField(max_length=2),
        ),
    ]
