# Generated by Django 3.2 on 2022-11-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_delete_fileupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('created_at', models.DateField()),
            ],
        ),
    ]
