# Generated by Django 3.2 on 2022-11-22 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_fileupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SelectDocument',
        ),
    ]
