# Generated by Django 6.0.5 on 2026-05-20 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_alter_bank_branch_code_alter_bank_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='company',
        ),
    ]
