# Generated by Django 6.0.5 on 2026-05-20 22:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_remove_bank_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='bic',
        ),
        migrations.AddField(
            model_name='bank',
            name='swift',
            field=models.CharField(default=datetime.datetime(2026, 5, 20, 22, 47, 42, 306627), max_length=12, verbose_name='SWIFT'),
            preserve_default=False,
        ),
    ]
