# Generated by Django 3.2 on 2022-11-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_delete_selectdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolling_nb', models.CharField(max_length=3)),
                ('bank_code', models.CharField(max_length=7)),
                ('account_number', models.CharField(max_length=15)),
                ('date', models.CharField(max_length=10)),
                ('amount_credit', models.CharField(max_length=15)),
                ('amount_debit', models.CharField(max_length=15)),
            ],
        ),
    ]
