# Generated by Django 3.2 on 2022-11-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0012_oldaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolling_nb', models.CharField(max_length=3)),
                ('bank_code', models.CharField(max_length=7)),
                ('account_number', models.CharField(max_length=15)),
                ('new_balance_date', models.CharField(max_length=10)),
                ('amount_credit', models.CharField(max_length=15)),
                ('amount_debit', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolling_nb', models.CharField(max_length=3)),
                ('bank_code', models.CharField(max_length=7)),
                ('account_number', models.CharField(max_length=15)),
                ('operation_date', models.CharField(max_length=10)),
                ('operation_name', models.CharField(max_length=10)),
                ('amount_credit', models.CharField(max_length=15)),
                ('amount_debit', models.CharField(max_length=15)),
            ],
        ),
    ]
