# Generated by Django 6.0.5 on 2026-05-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0012_remove_bank_bic_bank_swift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='adresse',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='zip_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
