# Generated by Django 6.0.5 on 2026-05-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0014_alter_bank_code_alter_bank_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountnumber',
            name='rib_key',
        ),
        migrations.AddField(
            model_name='accountnumber',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accountnumber',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=123456, max_digits=10),
            preserve_default=False,
        ),
    ]
