# Generated by Django 6.0.5 on 2026-05-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0015_remove_accountnumber_rib_key_accountnumber_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountnumber',
            name='currency',
            field=models.CharField(choices=[('E', 'Eur'), ('U', 'Usr'), ('C', 'Cny')], default='E', max_length=1),
        ),
    ]
