# Generated by Django 6.0.5 on 2026-05-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0016_accountnumber_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementfile',
            name='checked_file',
            field=models.BooleanField(default=False),
        ),
    ]
