# Generated by Django 6.0.5 on 2026-05-21 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0017_bankstatementfile_checked_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankstatementfile',
            old_name='checked_file',
            new_name='checked',
        ),
    ]
