# Generated by Django 6.0.5 on 2026-05-23 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0018_rename_checked_file_bankstatementfile_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountnumber',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='bank.bank'),
        ),
    ]
