# Generated by Django 6.0.5 on 2026-05-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0019_alter_accountnumber_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementfile',
            name='bank_code',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
