# Generated by Django 6.0.5 on 2026-05-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0020_bankstatementfile_bank_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatementfile',
            name='bank_code',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
