# Generated by Django 6.0.5 on 2026-05-23 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0021_alter_bankstatementfile_bank_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankstatementfile',
            name='bank_code',
        ),
        migrations.AddField(
            model_name='bankstatementfile',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.bank'),
        ),
        migrations.AlterField(
            model_name='accountnumber',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='bank.bank'),
        ),
    ]
