# Generated by Django 6.0.5 on 2026-05-23 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0022_remove_bankstatementfile_bank_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='lable',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
