# Generated by Django 6.0.5 on 2026-05-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0023_operation_lable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='lable',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='operation_label',
        ),
        migrations.AddField(
            model_name='operation',
            name='label',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
