# Generated by Django 6.0.5 on 2026-05-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0024_remove_operation_lable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='credit_or_debit',
            field=models.CharField(choices=[('C', 'Credit'), ('D', 'Debit'), ('N', 'Label')], max_length=1),
        ),
    ]
