# Generated by Django 6.0.5 on 2026-05-24 18:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0025_alter_operation_credit_or_debit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('E', 'Eur'), ('U', 'Usr'), ('C', 'Cny')], default='E', max_length=1)),
                ('active', models.BooleanField(default=True)),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='bank.bank')),
            ],
        ),
        migrations.AlterField(
            model_name='operation',
            name='account_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.account'),
        ),
        migrations.DeleteModel(
            name='AccountNumber',
        ),
    ]
