# Generated by Django 6.0.5 on 2026-05-24 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0026_account_alter_operation_account_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='account_number',
            new_name='account',
        ),
    ]
