# Generated by Django 6.0.5 on 2026-05-25 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0027_rename_account_number_operation_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='date_pointed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='pointed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operation',
            name='pointer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
