# Generated by Django 6.0.5 on 2026-05-30 08:25

import django.db.models.deletion
import uuid
from django.db import migrations, models

def fill_company_bank(apps, schema_editor):
    CompanyBank = apps.get_model('bank', 'CompanyBank')
    Bank = apps.get_model('bank', 'Bank')
    Company = apps.get_model('bank', 'Company')
    f_and_ch = Company.objects.get(company_email="fcs@yahoo.fr")
    b_t = Company.objects.get(company_email="Victoire@mail.fr")
    for bank in Bank.objects.all():
        company_bank = CompanyBank(
            company=f_and_ch,
            bank=bank,
            swift=bank.swift
        )
        if bank.swift == "BREDFRPPXXX":
            company_bank = CompanyBank(
                company=b_t,
                bank=bank,
                swift=bank.swift
            )
        company_bank.save()

def reverse(apps, schema_editor):
    CompanyBank = apps.get_model('bank', 'CompanyBank')
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0029_remove_company_user_company_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('swift', models.CharField(max_length=12, verbose_name='SWIFT')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_banks', to='bank.bank')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_banks', to='bank.company')),
            ],
            options={
                'unique_together': {('company', 'bank', 'swift')},
            },
        ),
        migrations.RunPython(fill_company_bank, reverse_code=reverse)
    ]
